<?php

/**
 * The curated /work set.
 *
 * Copy uses the "English||Bahasa Indonesia" shorthand (see Works::pair).
 * Placeholder narrative — replace metrics, document names and gallery media
 * with the real project material.
 *
 * Optional media keys per gallery item:
 *   'src'   → path under public/ for a still image
 *   'video' → path under public/ for an mp4 (renders a real <video>)
 *   'poster'→ path under public/ for the video poster
 * With none of these the item falls back to generated artwork.
 */

return [

    [
        'slug' => 'bri-debit-virtual-tvc',
        'title' => 'BRI Debit Virtual TVC',
        'client' => 'Bank Rakyat Indonesia',
        'logo' => 'assets/img/clients/bri.webp',
        'category' => 'Production',
        'division' => 'Production House||Rumah Produksi',
        'year' => '2025',
        'scope' => 'Concept — Script — Production — Post||Konsep — Naskah — Produksi — Pasca',
        'bg' => '#0e3c8c',
        'accent' => '#3ddc97',
        'tags' => ['TVC', 'Brand film', 'Post-production', 'Social cutdowns'],
        'lede' => 'A national commercial for a debit card that has no plastic — shot, cut and cleared for broadcast in six weeks.||Iklan nasional untuk kartu debit tanpa fisik — syuting, edit, dan lolos tayang dalam enam minggu.',
        'about' => [
            'BRImo\'s virtual debit card had no physical object to film, no packaging to unbox, and a compliance list longer than the script. The commercial had to make an invisible product feel safer than a plastic one.||Kartu debit virtual BRImo tidak punya objek fisik untuk difilmkan, tidak ada kemasan untuk dibuka, dan daftar kepatuhan yang lebih panjang dari naskahnya. Iklan ini harus membuat produk tak kasat mata terasa lebih aman daripada kartu plastik.',
            'We built the story around the two seconds after someone realises they can pay without carrying anything, then produced every screen frame in advance so legal signed off on the exact pixels that went to air.||Kami membangun cerita dari dua detik setelah seseorang sadar bisa membayar tanpa membawa apa pun, lalu memproduksi seluruh frame layar lebih dulu agar tim legal menyetujui piksel yang persis tayang.',
        ],
        'steps' => [
            ['h' => 'Found the human moment||Menemukan momen manusia', 'p' => 'We stopped selling the card and started filming the relief of not needing one — a queue, a phone, a tap, done.||Kami berhenti menjual kartunya dan mulai memfilmkan kelegaan karena tidak membutuhkannya — antre, ponsel, satu ketuk, selesai.'],
            ['h' => 'Built the UI in camera||Membangun UI di kamera', 'p' => 'Screen content was pre-rendered and played back on set, so compliance approved the exact frames that shipped instead of a mock-up.||Konten layar dirender lebih dulu dan diputar di lokasi syuting, sehingga tim kepatuhan menyetujui frame yang benar-benar tayang, bukan mock-up.'],
            ['h' => 'Cut once, delivered nine ways||Sekali edit, sembilan format', 'p' => 'One shoot produced the 30s TVC, three 15s cutdowns, vertical social edits and in-branch LED loops.||Satu kali syuting menghasilkan TVC 30 detik, tiga cutdown 15 detik, edit vertikal untuk sosial, dan loop LED di cabang.'],
        ],
        'stats' => [
            ['n' => '9', 'l' => 'Deliverables from one shoot||Deliverable dari satu syuting'],
            ['n' => '6', 'suffix' => 'wk', 'l' => 'Brief to broadcast||Brief ke tayang'],
            ['n' => '0', 'l' => 'Compliance reshoots||Syuting ulang kepatuhan'],
            ['n' => '3', 'l' => 'Channels live the same week||Kanal tayang pekan yang sama'],
        ],
        'gallery' => [
            ['kind' => 'Film||Film', 'cap' => 'Master 30s TVC — broadcast cut||Master TVC 30 detik — versi siar', 'video' => true],
            ['kind' => 'Still||Foto', 'cap' => 'Opening frame — the queue||Frame pembuka — antrean'],
            ['kind' => 'Still||Foto', 'cap' => 'Screen playback rig on set||Rig playback layar di lokasi'],
            ['kind' => 'Frame||Frame', 'cap' => 'Pre-rendered app UI sequence||Sekuens UI aplikasi pra-render'],
            ['kind' => 'Cutdown||Cutdown', 'cap' => 'Vertical 9:16 social edit||Edit sosial vertikal 9:16', 'video' => true],
            ['kind' => 'Still||Foto', 'cap' => 'In-branch LED loop||Loop LED di cabang'],
        ],
        'docs' => [
            ['label' => 'Creative treatment||Treatment kreatif', 'meta' => 'PDF — 24 pages||PDF — 24 halaman'],
            ['label' => 'Shooting board & script||Papan syuting & naskah', 'meta' => 'PDF — 41 pages||PDF — 41 halaman'],
            ['label' => 'Compliance frame log||Log frame kepatuhan', 'meta' => 'XLSX'],
            ['label' => 'Delivery spec — 9 masters||Spesifikasi delivery — 9 master', 'meta' => 'PDF'],
        ],
        'usecases' => [
            ['h' => 'National television||Televisi nasional', 'p' => 'The 30s master ran across national free-to-air and pay TV during the launch quarter.||Master 30 detik tayang di TV nasional free-to-air dan berbayar sepanjang kuartal peluncuran.'],
            ['h' => 'Performance social||Sosial performa', 'p' => 'Vertical cutdowns fed Instagram Reels, TikTok and YouTube Shorts with the same colour pipeline.||Cutdown vertikal mengisi Instagram Reels, TikTok, dan YouTube Shorts dengan pipeline warna yang sama.'],
            ['h' => 'Branch & ATM screens||Layar cabang & ATM', 'p' => 'A silent 12s loop, legible without audio, plays on in-branch LED and ATM idle screens.||Loop senyap 12 detik yang terbaca tanpa audio diputar di LED cabang dan layar idle ATM.'],
        ],
        'credits' => [
            ['role' => 'Concept & script||Konsep & naskah', 'name' => 'Fugo Creative'],
            ['role' => 'Production||Produksi', 'name' => 'Fugo Production House'],
            ['role' => 'Post & colour||Pasca & warna', 'name' => 'Fugo Post'],
            ['role' => 'Client team||Tim klien', 'name' => 'BRI Marketing Communication'],
        ],
        'case_study' => 'case-study',
    ],

    [
        'slug' => 'daihatsu-dealer-campaign-system',
        'title' => 'Dealer Campaign System',
        'client' => 'Daihatsu',
        'logo' => 'assets/img/clients/daihatsu1.webp',
        'category' => 'Design',
        'division' => 'Design||Desain',
        'year' => '2024',
        'scope' => 'Design system — Templates — Rollout||Sistem desain — Template — Rollout',
        'bg' => '#2a1116',
        'accent' => '#ff6b4a',
        'tags' => ['Design system', 'Templates', 'Print & digital', 'Rollout'],
        'lede' => 'One campaign kit that 200+ dealers can localise in an afternoon without breaking the brand.||Satu kit kampanye yang bisa dilokalkan 200+ dealer dalam satu sore tanpa merusak brand.',
        'about' => [
            'Every dealer was rebuilding national campaign material by hand — different fonts, stretched logos, promo prices in twenty different colours. The brand looked like twenty brands by the time it reached a showroom window.||Setiap dealer membangun ulang materi kampanye nasional secara manual — font berbeda, logo melar, harga promo dalam dua puluh warna. Brand terlihat seperti dua puluh brand begitu sampai di etalase showroom.',
            'We replaced the free-for-all with a locked template system: fixed type, fixed grid, editable price, editable address, editable photo — and nothing else.||Kami mengganti kebebasan itu dengan sistem template terkunci: tipografi tetap, grid tetap, harga bisa diubah, alamat bisa diubah, foto bisa diubah — selain itu tidak.',
        ],
        'steps' => [
            ['h' => 'Audited what dealers actually make||Mengaudit yang benar-benar dibuat dealer', 'p' => 'Six weeks of collecting real dealer artwork showed the same eleven formats being rebuilt over and over.||Enam minggu mengumpulkan materi asli dealer menunjukkan sebelas format yang sama dibangun ulang berkali-kali.'],
            ['h' => 'Locked the grid, freed the content||Mengunci grid, membebaskan konten', 'p' => 'Type, logo clear space and colour are hard-locked; price, unit photo and dealer details are the only editable layers.||Tipografi, clear space logo, dan warna dikunci; harga, foto unit, dan detail dealer adalah satu-satunya lapisan yang bisa diedit.'],
            ['h' => 'Shipped it as a kit, not a PDF||Dikirim sebagai kit, bukan PDF', 'p' => 'Editable files, a one-page rule sheet and a 4-minute screen recording — enough for a dealer admin with no design background.||File siap edit, satu halaman aturan, dan rekaman layar 4 menit — cukup untuk admin dealer tanpa latar desain.'],
        ],
        'stats' => [
            ['n' => '200', 'suffix' => '+', 'l' => 'Dealer points on the system||Titik dealer memakai sistem'],
            ['n' => '11', 'l' => 'Locked formats||Format terkunci'],
            ['n' => '85', 'suffix' => '%', 'l' => 'Less artwork rework||Pengerjaan ulang berkurang'],
            ['n' => '1', 'suffix' => 'd', 'l' => 'Campaign to showroom||Kampanye ke showroom'],
        ],
        'gallery' => [
            ['kind' => 'System||Sistem', 'cap' => 'Master grid and type scale||Grid master dan skala tipografi'],
            ['kind' => 'Template||Template', 'cap' => 'Showroom banner — 3 sizes||Banner showroom — 3 ukuran'],
            ['kind' => 'Template||Template', 'cap' => 'Price tag and unit spec card||Label harga dan kartu spesifikasi'],
            ['kind' => 'Digital||Digital', 'cap' => 'Feed, story and WhatsApp status set||Set feed, story, dan status WhatsApp'],
            ['kind' => 'Print||Cetak', 'cap' => 'A3 poster and roll-up banner||Poster A3 dan roll-up banner'],
            ['kind' => 'Guide||Panduan', 'cap' => 'One-page dealer rule sheet||Satu halaman aturan dealer'],
        ],
        'docs' => [
            ['label' => 'Dealer brand guideline||Panduan brand dealer', 'meta' => 'PDF — 38 pages||PDF — 38 halaman'],
            ['label' => 'Editable template pack||Paket template siap edit', 'meta' => 'AI / INDD / PSD'],
            ['label' => 'Print spec & material list||Spesifikasi cetak & daftar material', 'meta' => 'PDF'],
            ['label' => 'How-to screen recording||Rekaman layar cara pakai', 'meta' => 'MP4 — 4 min||MP4 — 4 menit'],
        ],
        'usecases' => [
            ['h' => 'Monthly national promo||Promo nasional bulanan', 'p' => 'Head office drops the campaign key visual; dealers publish localised versions the same day.||Kantor pusat merilis key visual kampanye; dealer menerbitkan versi lokal di hari yang sama.'],
            ['h' => 'Showroom & event||Showroom & pameran', 'p' => 'The same grid scales from a price tag to a 3×2 m exhibition wall without redrawing anything.||Grid yang sama menskala dari label harga hingga dinding pameran 3×2 m tanpa menggambar ulang.'],
            ['h' => 'Sales team WhatsApp||WhatsApp tim penjualan', 'p' => 'A 1080×1920 status template keeps salesperson-level posts on brand.||Template status 1080×1920 menjaga unggahan personal tenaga penjual tetap sesuai brand.'],
        ],
        'credits' => [
            ['role' => 'Design system||Sistem desain', 'name' => 'Fugo Design'],
            ['role' => 'Art direction||Pengarahan seni', 'name' => 'Fugo Creative'],
            ['role' => 'Rollout & training||Rollout & pelatihan', 'name' => 'Fugo Brand Ops'],
            ['role' => 'Client team||Tim klien', 'name' => 'Daihatsu Marketing'],
        ],
        'case_study' => null,
    ],

    [
        'slug' => 'kemenhub-national-transport-expo',
        'title' => 'National Transport Expo',
        'client' => 'Kemenhub',
        'logo' => 'assets/img/clients/Kemenhub.webp',
        'category' => 'Events',
        'division' => 'Events||Acara',
        'year' => '2024',
        'scope' => 'Concept — Build — Show running||Konsep — Bangun — Show running',
        'bg' => '#0b2545',
        'accent' => '#4b5cff',
        'tags' => ['Exhibition', 'Stage', 'Wayfinding', 'Show running'],
        'lede' => 'Three days, eleven zones and a ministerial opening — built in a hall that was still empty 72 hours earlier.||Tiga hari, sebelas zona, dan pembukaan tingkat menteri — dibangun di hall yang 72 jam sebelumnya masih kosong.',
        'about' => [
            'A public expo has two audiences that want opposite things: officials who need a protocol-perfect ceremony, and families who want somewhere to walk, look and take photos.||Expo publik punya dua audiens dengan keinginan berlawanan: pejabat yang butuh seremoni sesuai protokol, dan keluarga yang ingin berjalan, melihat, dan berfoto.',
            'We planned the floor as a single loop so the ceremony route and the public route never collide, then treated wayfinding as the main design object rather than an afterthought.||Kami merancang lantai sebagai satu loop agar rute seremoni dan rute publik tidak pernah bertabrakan, lalu memperlakukan wayfinding sebagai objek desain utama, bukan pelengkap.',
        ],
        'steps' => [
            ['h' => 'One loop, two routes||Satu loop, dua rute', 'p' => 'The ceremony walk and the visitor flow share a floor but never cross — no rope lines, no bottlenecks.||Rute seremoni dan alur pengunjung berbagi lantai tetapi tidak pernah bersinggungan — tanpa tali pembatas, tanpa penumpukan.'],
            ['h' => 'Modular zones||Zona modular', 'p' => 'Eleven zones from one structural kit, so a late change to the floor plan cost hours instead of days.||Sebelas zona dari satu kit struktur, sehingga perubahan denah di menit akhir memakan jam, bukan hari.'],
            ['h' => 'Rehearsed the whole show||Menggeladi seluruh acara', 'p' => 'A full technical run the night before covered cues, audio, LED and the protocol sequence end to end.||Gladi teknis penuh semalam sebelumnya mencakup cue, audio, LED, dan urutan protokol dari awal sampai akhir.'],
        ],
        'stats' => [
            ['n' => '11', 'l' => 'Exhibition zones||Zona pameran'],
            ['n' => '3', 'suffix' => 'd', 'l' => 'Show days||Hari acara'],
            ['n' => '72', 'suffix' => 'h', 'l' => 'Empty hall to open doors||Hall kosong ke pintu buka'],
            ['n' => '24', 'suffix' => 'k', 'l' => 'Visitors across the run||Pengunjung sepanjang acara'],
        ],
        'gallery' => [
            ['kind' => 'Plan||Denah', 'cap' => 'Floor plan — loop circulation||Denah lantai — sirkulasi loop'],
            ['kind' => 'Build||Bangun', 'cap' => 'Main stage structure||Struktur panggung utama'],
            ['kind' => 'Still||Foto', 'cap' => 'Opening ceremony||Seremoni pembukaan'],
            ['kind' => 'System||Sistem', 'cap' => 'Wayfinding and zone signage||Wayfinding dan penanda zona'],
            ['kind' => 'Film||Film', 'cap' => 'Three-day event recap||Rekap acara tiga hari', 'video' => true],
            ['kind' => 'Still||Foto', 'cap' => 'Interactive zone at peak hour||Zona interaktif di jam ramai'],
        ],
        'docs' => [
            ['label' => 'Event concept deck||Deck konsep acara', 'meta' => 'PDF — 52 pages||PDF — 52 halaman'],
            ['label' => 'Floor plan & rigging drawings||Denah & gambar rigging', 'meta' => 'DWG / PDF'],
            ['label' => 'Run-down & cue sheet||Rundown & cue sheet', 'meta' => 'XLSX'],
            ['label' => 'Safety and crowd flow plan||Rencana keselamatan & alur massa', 'meta' => 'PDF'],
            ['label' => 'Post-event report||Laporan pasca acara', 'meta' => 'PDF — 30 pages||PDF — 30 halaman'],
        ],
        'usecases' => [
            ['h' => 'Ministerial protocol||Protokol kementerian', 'p' => 'A fixed ceremony route, timed to the minute, cleared with protocol staff before build started.||Rute seremoni tetap, dihitung per menit, disetujui staf protokol sebelum pembangunan dimulai.'],
            ['h' => 'Public open days||Hari terbuka publik', 'p' => 'Wayfinding tested for first-time visitors — every zone reachable without asking staff.||Wayfinding diuji untuk pengunjung baru — setiap zona bisa dicapai tanpa bertanya ke petugas.'],
            ['h' => 'Press and documentation||Pers dan dokumentasi', 'p' => 'Camera positions and a media room were designed into the plan, not squeezed in later.||Posisi kamera dan ruang media dirancang sejak denah, bukan diselipkan belakangan.'],
        ],
        'credits' => [
            ['role' => 'Event concept||Konsep acara', 'name' => 'Fugo Events'],
            ['role' => 'Production & build||Produksi & bangun', 'name' => 'Fugo Events'],
            ['role' => 'Graphics & wayfinding||Grafis & wayfinding', 'name' => 'Fugo Design'],
            ['role' => 'Documentation||Dokumentasi', 'name' => 'Fugo Production House'],
        ],
        'case_study' => null,
    ],

    [
        'slug' => 'telkomsel-partner-welcome-kit',
        'title' => 'Partner Welcome Kit',
        'client' => 'Telkomsel',
        'logo' => 'assets/img/clients/telkomsel.webp',
        'category' => 'Merch',
        'division' => 'Merchandise||Merchandise',
        'year' => '2023',
        'scope' => 'Design — Sourcing — QC — Fulfilment||Desain — Sourcing — QC — Pengiriman',
        'bg' => '#5a1414',
        'accent' => '#ff6b4a',
        'tags' => ['Merchandise', 'Packaging', 'Sourcing', 'Fulfilment'],
        'lede' => '12,000 onboarding kits designed, produced and delivered across 34 provinces without a single reprint.||12.000 kit onboarding dirancang, diproduksi, dan dikirim ke 34 provinsi tanpa sekali pun cetak ulang.',
        'about' => [
            'A welcome kit is a logistics problem wearing a design brief. It has to survive a courier, open well on camera, and cost the same whether it lands in Jakarta or Jayapura.||Welcome kit adalah masalah logistik yang menyamar sebagai brief desain. Ia harus selamat dari kurir, terbuka bagus di kamera, dan berbiaya sama entah mendarat di Jakarta atau Jayapura.',
            'We designed the box around the shipping carton, not the other way round, and picked items by how well they survive three months of daily use rather than how they photograph on day one.||Kami merancang boks mengikuti karton pengiriman, bukan sebaliknya, dan memilih item berdasarkan ketahanan tiga bulan pemakaian harian, bukan penampilannya di hari pertama.',
        ],
        'steps' => [
            ['h' => 'Designed for the courier||Merancang untuk kurir', 'p' => 'Box dimensions were set by the cheapest protective shipping size, which removed a layer of packaging entirely.||Dimensi boks ditentukan ukuran pengiriman terlindungi termurah, sehingga satu lapis kemasan hilang sepenuhnya.'],
            ['h' => 'Sampled before committing||Sampel sebelum komitmen', 'p' => 'Three vendors, one sample round, one wash-and-wear test — then a single production order.||Tiga vendor, satu putaran sampel, satu uji cuci-pakai — lalu satu order produksi.'],
            ['h' => 'QC at the packing line||QC di jalur pengepakan', 'p' => 'Kits were checked as they were packed, not after, so defects never entered the shipment count.||Kit diperiksa saat dikemas, bukan setelahnya, sehingga cacat tidak pernah masuk hitungan pengiriman.'],
        ],
        'stats' => [
            ['n' => '12', 'suffix' => 'k', 'l' => 'Kits shipped||Kit terkirim'],
            ['n' => '34', 'l' => 'Provinces covered||Provinsi terjangkau'],
            ['n' => '7', 'l' => 'Items per kit||Item per kit'],
            ['n' => '0', 'l' => 'Reprints||Cetak ulang'],
        ],
        'gallery' => [
            ['kind' => 'Packaging||Kemasan', 'cap' => 'Outer box and sleeve||Boks luar dan sleeve'],
            ['kind' => 'Still||Foto', 'cap' => 'Full kit laid out||Kit lengkap tertata'],
            ['kind' => 'Product||Produk', 'cap' => 'Apparel and lanyard||Apparel dan lanyard'],
            ['kind' => 'Product||Produk', 'cap' => 'Notebook and welcome card||Notes dan kartu sambutan'],
            ['kind' => 'Film||Film', 'cap' => 'Unboxing sequence||Sekuens unboxing', 'video' => true],
            ['kind' => 'Process||Proses', 'cap' => 'Packing line and QC station||Jalur pengepakan dan stasiun QC'],
        ],
        'docs' => [
            ['label' => 'Kit design & dieline pack||Paket desain & dieline', 'meta' => 'AI / PDF'],
            ['label' => 'Material and vendor spec||Spesifikasi material & vendor', 'meta' => 'XLSX'],
            ['label' => 'QC checklist||Checklist QC', 'meta' => 'PDF'],
            ['label' => 'Distribution manifest||Manifes distribusi', 'meta' => 'XLSX — 34 provinces||XLSX — 34 provinsi'],
        ],
        'usecases' => [
            ['h' => 'Partner onboarding||Onboarding mitra', 'p' => 'Sent on contract signing — the kit is the first physical thing a new partner receives.||Dikirim saat penandatanganan kontrak — kit adalah benda fisik pertama yang diterima mitra baru.'],
            ['h' => 'Regional roadshow||Roadshow daerah', 'p' => 'The same kit doubles as event handout stock, packed flat and assembled on site.||Kit yang sama menjadi stok bingkisan acara, dikemas datar dan dirakit di lokasi.'],
            ['h' => 'Internal recognition||Apresiasi internal', 'p' => 'A trimmed three-item version is used for quarterly team awards.||Versi ringkas tiga item digunakan untuk penghargaan tim tiap kuartal.'],
        ],
        'credits' => [
            ['role' => 'Kit design||Desain kit', 'name' => 'Fugo Design'],
            ['role' => 'Sourcing & QC||Sourcing & QC', 'name' => 'Fugo Merch'],
            ['role' => 'Fulfilment||Pengiriman', 'name' => 'Fugo Merch'],
            ['role' => 'Client team||Tim klien', 'name' => 'Telkomsel Partnership'],
        ],
        'case_study' => null,
    ],

    [
        'slug' => 'bank-mandiri-annual-report-2023',
        'title' => 'Annual Report 2023',
        'client' => 'Bank Mandiri',
        'logo' => 'assets/img/clients/mandiri.webp',
        'category' => 'Design',
        'division' => 'Design||Desain',
        'year' => '2023',
        'scope' => 'Editorial design — Data viz — Print||Desain editorial — Visualisasi data — Cetak',
        'bg' => '#0a2f4a',
        'accent' => '#c8f24e',
        'tags' => ['Editorial', 'Data visualisation', 'Print', 'Digital edition'],
        'lede' => '340 pages of regulated disclosure that a non-accountant can actually read.||340 halaman pengungkapan teregulasi yang bisa dibaca orang non-akuntan.',
        'about' => [
            'An annual report has no room to be clever: the structure is dictated by regulation and the numbers cannot move. The only design variable left is whether a reader can find anything.||Laporan tahunan tidak punya ruang untuk gaya-gayaan: strukturnya ditentukan regulasi dan angkanya tidak bisa digeser. Satu-satunya variabel desain yang tersisa adalah apakah pembaca bisa menemukan sesuatu.',
            'We rebuilt the grid around scanning behaviour — running headers, a fixed table language, and one chart style used consistently for 340 pages.||Kami membangun ulang grid mengikuti perilaku memindai — running header, bahasa tabel yang tetap, dan satu gaya grafik yang konsisten sepanjang 340 halaman.',
        ],
        'steps' => [
            ['h' => 'Fixed the table language||Menetapkan bahasa tabel', 'p' => 'One table style, one number alignment, one rule weight — applied to every financial statement in the book.||Satu gaya tabel, satu perataan angka, satu ketebalan garis — diterapkan ke seluruh laporan keuangan di dalamnya.'],
            ['h' => 'Charted the story, not the spreadsheet||Menggrafikkan cerita, bukan spreadsheet', 'p' => 'Each chapter opens with one chart that answers the chapter\'s question, before the detail tables begin.||Setiap bab dibuka dengan satu grafik yang menjawab pertanyaan bab itu, sebelum tabel detail dimulai.'],
            ['h' => 'Print and screen from one file||Cetak dan layar dari satu file', 'p' => 'The digital edition is generated from the same layout, so late number changes only had to be made once.||Edisi digital dihasilkan dari layout yang sama, sehingga perubahan angka di menit akhir cukup dilakukan sekali.'],
        ],
        'stats' => [
            ['n' => '340', 'l' => 'Pages designed||Halaman dirancang'],
            ['n' => '96', 'l' => 'Charts and tables||Grafik dan tabel'],
            ['n' => '2', 'l' => 'Languages in one grid||Bahasa dalam satu grid'],
            ['n' => '1', 'l' => 'Source file for print and web||Satu file sumber untuk cetak dan web'],
        ],
        'gallery' => [
            ['kind' => 'Spread||Spread', 'cap' => 'Cover and chapter opener||Sampul dan pembuka bab'],
            ['kind' => 'System||Sistem', 'cap' => 'Grid and running header logic||Grid dan logika running header'],
            ['kind' => 'Data||Data', 'cap' => 'Chart language — 6 base types||Bahasa grafik — 6 tipe dasar'],
            ['kind' => 'Spread||Spread', 'cap' => 'Financial statement tables||Tabel laporan keuangan'],
            ['kind' => 'Print||Cetak', 'cap' => 'Bound copy and paper stock||Buku terjilid dan pilihan kertas'],
            ['kind' => 'Digital||Digital', 'cap' => 'Screen edition and index||Edisi layar dan indeks'],
        ],
        'docs' => [
            ['label' => 'Editorial grid guideline||Panduan grid editorial', 'meta' => 'PDF — 22 pages||PDF — 22 halaman'],
            ['label' => 'Chart and table style sheet||Style sheet grafik & tabel', 'meta' => 'PDF'],
            ['label' => 'Print production spec||Spesifikasi produksi cetak', 'meta' => 'PDF'],
            ['label' => 'Digital edition build notes||Catatan build edisi digital', 'meta' => 'PDF'],
        ],
        'usecases' => [
            ['h' => 'Regulatory filing||Pelaporan regulator', 'p' => 'The printed edition meets OJK disclosure structure without design workarounds.||Edisi cetak memenuhi struktur pengungkapan OJK tanpa akal-akalan desain.'],
            ['h' => 'Investor relations||Hubungan investor', 'p' => 'Chapter-opening charts double as ready-made slides for analyst briefings.||Grafik pembuka bab sekaligus menjadi slide siap pakai untuk paparan analis.'],
            ['h' => 'Internal reference||Rujukan internal', 'p' => 'The table language became the default for quarterly reporting the following year.||Bahasa tabelnya menjadi standar pelaporan kuartalan di tahun berikutnya.'],
        ],
        'credits' => [
            ['role' => 'Editorial design||Desain editorial', 'name' => 'Fugo Design'],
            ['role' => 'Data visualisation||Visualisasi data', 'name' => 'Fugo Design'],
            ['role' => 'Print production||Produksi cetak', 'name' => 'Fugo Production'],
            ['role' => 'Client team||Tim klien', 'name' => 'Bank Mandiri Corporate Secretary'],
        ],
        'case_study' => null,
    ],
    [
        'slug' => 'citilink-cabin-crew-uniform-line',
        'title' => 'Cabin Crew Uniform Line',
        'client' => 'Citilink',
        'logo' => 'assets/img/clients/citylink.webp',
        'category' => 'Merch',
        'division' => 'Merchandise||Merchandise',
        'year' => '2023',
        'scope' => 'Design — Fit trials — Production||Desain — Uji fit — Produksi',
        'bg' => '#0f3d2e',
        'accent' => '#3ddc97',
        'tags' => ['Apparel', 'Fit engineering', 'Production', 'Size system'],
        'lede' => 'A uniform line judged by a ten-hour shift, not a photo shoot.||Lini seragam yang dinilai oleh shift sepuluh jam, bukan oleh sesi foto.',
        'about' => [
            'Crew uniforms fail in the details nobody photographs: a seam that rubs under a harness, a fabric that shows every crease by the third sector, a size chart that fits a sample body and nobody else.||Seragam kru gagal pada detail yang tidak difoto siapa pun: jahitan yang menggesek di bawah harness, bahan yang menampakkan setiap lipatan di sektor ketiga, dan tabel ukuran yang hanya pas untuk tubuh sampel.',
            'We ran fit trials on working crew across real rosters before a single production unit was cut.||Kami menjalankan uji fit pada kru yang benar-benar bertugas di roster nyata sebelum satu unit produksi pun dipotong.',
        ],
        'steps' => [
            ['h' => 'Trialled on real shifts||Diuji di shift sebenarnya', 'p' => 'Prototypes were worn on full rosters, then scored on movement, heat and creasing rather than looks.||Prototipe dipakai sepanjang roster penuh, lalu dinilai berdasarkan gerak, panas, dan kekusutan — bukan tampilan.'],
            ['h' => 'Rebuilt the size system||Membangun ulang sistem ukuran', 'p' => 'Measured grading across the actual crew population replaced an inherited generic size chart.||Grading terukur dari populasi kru asli menggantikan tabel ukuran generik warisan.'],
            ['h' => 'Specced for replacement||Merancang untuk penggantian', 'p' => 'Every component is separately re-orderable, so a damaged item does not retire a whole set.||Setiap komponen bisa dipesan ulang terpisah, sehingga satu item rusak tidak memensiunkan seluruh set.'],
        ],
        'stats' => [
            ['n' => '6', 'l' => 'Garment pieces in the line||Potongan busana dalam lini'],
            ['n' => '3', 'l' => 'Fit trial rounds||Putaran uji fit'],
            ['n' => '18', 'l' => 'Sizes in the final grade||Ukuran dalam grading akhir'],
            ['n' => '92', 'suffix' => '%', 'l' => 'Crew fit satisfaction||Kepuasan fit kru'],
        ],
        'gallery' => [
            ['kind' => 'Design||Desain', 'cap' => 'Line-up — full uniform set||Line-up — set seragam lengkap'],
            ['kind' => 'Technical||Teknis', 'cap' => 'Construction and seam detail||Konstruksi dan detail jahitan'],
            ['kind' => 'Material||Material', 'cap' => 'Fabric and colourway tests||Uji bahan dan colourway'],
            ['kind' => 'Process||Proses', 'cap' => 'Fit trial on roster||Uji fit saat bertugas'],
            ['kind' => 'Still||Foto', 'cap' => 'In-service portrait||Potret saat bertugas'],
            ['kind' => 'System||Sistem', 'cap' => 'Size grading chart||Tabel grading ukuran'],
        ],
        'docs' => [
            ['label' => 'Garment tech pack||Tech pack busana', 'meta' => 'PDF — 46 pages||PDF — 46 halaman'],
            ['label' => 'Fabric and trim spec||Spesifikasi bahan & aksesori', 'meta' => 'PDF'],
            ['label' => 'Size grading chart||Tabel grading ukuran', 'meta' => 'XLSX'],
            ['label' => 'Care and replacement guide||Panduan perawatan & penggantian', 'meta' => 'PDF'],
        ],
        'usecases' => [
            ['h' => 'Daily line operations||Operasi harian', 'p' => 'Built for a ten-hour duty day, including galley work and repeated harness use.||Dirancang untuk hari tugas sepuluh jam, termasuk kerja galley dan pemakaian harness berulang.'],
            ['h' => 'Recruitment and training||Rekrutmen dan pelatihan', 'p' => 'A trainee variant marks status clearly without a second production run.||Varian trainee menandai status dengan jelas tanpa produksi terpisah.'],
            ['h' => 'Brand appearances||Penampilan brand', 'p' => 'The same line reads correctly on camera for campaign and press use.||Lini yang sama tetap terbaca di kamera untuk kebutuhan kampanye dan pers.'],
        ],
        'credits' => [
            ['role' => 'Apparel design||Desain busana', 'name' => 'Fugo Merch'],
            ['role' => 'Fit engineering||Rekayasa fit', 'name' => 'Fugo Merch'],
            ['role' => 'Production||Produksi', 'name' => 'Fugo Merch'],
            ['role' => 'Client team||Tim klien', 'name' => 'Citilink Cabin Services'],
        ],
        'case_study' => null,
    ],

    [
        'slug' => 'bjb-syariah-ramadan-brand-film',
        'title' => 'Ramadan Brand Film',
        'client' => 'bjb Syariah',
        'logo' => 'assets/img/clients/bjb-syariah.webp',
        'category' => 'Production',
        'division' => 'Production House||Rumah Produksi',
        'year' => '2025',
        'scope' => 'Concept — Production — Post — Music||Konsep — Produksi — Pasca — Musik',
        'bg' => '#2a1a4a',
        'accent' => '#c8f24e',
        'tags' => ['Brand film', 'Seasonal', 'Music', 'Social edits'],
        'lede' => 'A Ramadan film that earns its emotion instead of borrowing it from a soundtrack.||Film Ramadan yang membangun emosinya sendiri, bukan meminjamnya dari soundtrack.',
        'about' => [
            'Every bank releases a Ramadan film, and most of them are the same film: slow motion, a table, a returning relative. The brief was to be recognisably bjb Syariah in the first five seconds without a logo.||Setiap bank merilis film Ramadan, dan kebanyakan adalah film yang sama: gerak lambat, sebuah meja, kerabat yang pulang. Briefnya adalah terasa sebagai bjb Syariah dalam lima detik pertama tanpa logo.',
            'We anchored the story in one specific act of saving rather than a generic homecoming, and scored it with an original arrangement so the film does not sound like the four beside it in the ad break.||Kami menambatkan cerita pada satu tindakan menabung yang spesifik alih-alih mudik generik, dan menggarap aransemen orisinal agar filmnya tidak terdengar seperti empat film lain di jeda iklan.',
        ],
        'steps' => [
            ['h' => 'Wrote one specific act||Menulis satu tindakan spesifik', 'p' => 'A single, small financial decision carries the whole film — no montage, no narration.||Satu keputusan finansial kecil menopang seluruh film — tanpa montase, tanpa narasi.'],
            ['h' => 'Scored it originally||Menggarap musik orisinal', 'p' => 'An original arrangement recorded for the cut, licensed outright for all channels and future years.||Aransemen orisinal direkam untuk versi finalnya, dilisensikan penuh untuk semua kanal dan tahun berikutnya.'],
            ['h' => 'Planned the cutdowns first||Merencanakan cutdown lebih dulu', 'p' => 'The 60s was blocked so that the 30s, 15s and 6s bumpers exist inside it, not as afterthought trims.||Versi 60 detik disusun agar versi 30, 15, dan bumper 6 detik sudah ada di dalamnya, bukan potongan dadakan.'],
        ],
        'stats' => [
            ['n' => '4', 'l' => 'Durations from one cut||Durasi dari satu edit'],
            ['n' => '1', 'l' => 'Original score||Musik orisinal'],
            ['n' => '5', 'suffix' => 'd', 'l' => 'Shoot days||Hari syuting'],
            ['n' => '30', 'suffix' => 'd', 'l' => 'Concept to air||Konsep ke tayang'],
        ],
        'gallery' => [
            ['kind' => 'Film||Film', 'cap' => 'Master 60s brand film||Master film brand 60 detik', 'video' => true],
            ['kind' => 'Still||Foto', 'cap' => 'Opening scene||Adegan pembuka'],
            ['kind' => 'Still||Foto', 'cap' => 'Golden-hour exterior||Eksterior golden hour'],
            ['kind' => 'Process||Proses', 'cap' => 'Scoring session||Sesi rekaman musik'],
            ['kind' => 'Cutdown||Cutdown', 'cap' => '15s broadcast cutdown||Cutdown siar 15 detik', 'video' => true],
            ['kind' => 'Frame||Frame', 'cap' => 'Colour grade reference||Referensi color grade'],
        ],
        'docs' => [
            ['label' => 'Creative treatment||Treatment kreatif', 'meta' => 'PDF — 18 pages||PDF — 18 halaman'],
            ['label' => 'Storyboard||Storyboard', 'meta' => 'PDF — 34 frames||PDF — 34 frame'],
            ['label' => 'Music licence & stems||Lisensi musik & stem', 'meta' => 'PDF / WAV'],
            ['label' => 'Delivery master list||Daftar master delivery', 'meta' => 'PDF'],
        ],
        'usecases' => [
            ['h' => 'Ramadan broadcast||Siaran Ramadan', 'p' => 'The 30s and 15s masters carried the on-air campaign through the fasting month.||Master 30 dan 15 detik menopang kampanye on-air sepanjang bulan puasa.'],
            ['h' => 'Branch and digital||Cabang dan digital', 'p' => 'Silent-legible versions play on branch screens and in-app placements.||Versi yang terbaca tanpa suara diputar di layar cabang dan penempatan dalam aplikasi.'],
            ['h' => 'Reusable next season||Bisa dipakai musim berikutnya', 'p' => 'Full music and talent rights mean the film can be re-cut for the following year.||Hak musik dan talenta penuh membuat film ini bisa diedit ulang untuk tahun berikutnya.'],
        ],
        'credits' => [
            ['role' => 'Concept & direction||Konsep & penyutradaraan', 'name' => 'Fugo Creative'],
            ['role' => 'Production||Produksi', 'name' => 'Fugo Production House'],
            ['role' => 'Music||Musik', 'name' => 'Fugo Sound'],
            ['role' => 'Client team||Tim klien', 'name' => 'bjb Syariah Marketing'],
        ],
        'case_study' => null,
    ],

    [
        'slug' => 'btpn-sales-kickoff-gathering',
        'title' => 'Sales Kickoff Gathering',
        'client' => 'BTPN',
        'logo' => 'assets/img/clients/btpn.webp',
        'category' => 'Events',
        'division' => 'Events||Acara',
        'year' => '2024',
        'scope' => 'Concept — Stage — Content — Show running||Konsep — Panggung — Konten — Show running',
        'bg' => '#3a2410',
        'accent' => '#ff6b4a',
        'tags' => ['Corporate event', 'Stage design', 'Live content', 'Awards'],
        'lede' => '900 sales people, one room, and a target announcement that had to land as motivation rather than pressure.||900 tenaga penjual, satu ruangan, dan pengumuman target yang harus terasa memotivasi, bukan menekan.',
        'about' => [
            'A kickoff lives or dies in the middle ninety minutes, when the numbers go up on screen. Everything before it is warm-up and everything after is celebration.||Kickoff hidup atau mati di sembilan puluh menit tengahnya, saat angka naik ke layar. Semua yang sebelumnya adalah pemanasan dan semua sesudahnya adalah perayaan.',
            'We designed the run-down backwards from that moment, and built the stage content so regional results could be updated on the day without a designer in the room.||Kami menyusun rundown mundur dari momen itu, dan membangun konten panggung agar hasil regional bisa diperbarui di hari-H tanpa desainer di ruangan.',
        ],
        'steps' => [
            ['h' => 'Built the run-down backwards||Menyusun rundown dari belakang', 'p' => 'The target reveal was fixed first; the rest of the day was scheduled around holding attention for it.||Momen pengumuman target ditetapkan lebih dulu; sisa acara dijadwalkan untuk menjaga perhatian menuju ke sana.'],
            ['h' => 'Templated the live content||Membuat template konten live', 'p' => 'Regional leaderboards update from a spreadsheet, so the operator changes numbers, never layouts.||Papan peringkat regional diperbarui dari spreadsheet, sehingga operator mengubah angka, bukan layout.'],
            ['h' => 'Rehearsed the awards||Menggeladi sesi penghargaan', 'p' => 'Name pronunciation, walk-up cues and photo positions were run twice before doors opened.||Pelafalan nama, cue naik panggung, dan posisi foto digeladi dua kali sebelum pintu dibuka.'],
        ],
        'stats' => [
            ['n' => '900', 'l' => 'Attendees||Peserta'],
            ['n' => '2', 'suffix' => 'd', 'l' => 'Programme days||Hari program'],
            ['n' => '48', 'l' => 'Awards handed on stage||Penghargaan diserahkan di panggung'],
            ['n' => '0', 'l' => 'Content resets during show||Reset konten saat acara'],
        ],
        'gallery' => [
            ['kind' => 'Build||Bangun', 'cap' => 'Main stage and LED array||Panggung utama dan susunan LED'],
            ['kind' => 'Still||Foto', 'cap' => 'Opening session||Sesi pembuka'],
            ['kind' => 'Content||Konten', 'cap' => 'Live leaderboard template||Template papan peringkat live'],
            ['kind' => 'Still||Foto', 'cap' => 'Awards walk-up||Prosesi penghargaan'],
            ['kind' => 'Film||Film', 'cap' => 'Two-day event recap||Rekap acara dua hari', 'video' => true],
            ['kind' => 'System||Sistem', 'cap' => 'Signage and registration||Signage dan registrasi'],
        ],
        'docs' => [
            ['label' => 'Event concept deck||Deck konsep acara', 'meta' => 'PDF — 40 pages||PDF — 40 halaman'],
            ['label' => 'Stage and LED drawings||Gambar panggung & LED', 'meta' => 'DWG / PDF'],
            ['label' => 'Run-down & cue sheet||Rundown & cue sheet', 'meta' => 'XLSX'],
            ['label' => 'Live content operator guide||Panduan operator konten live', 'meta' => 'PDF'],
        ],
        'usecases' => [
            ['h' => 'Annual kickoff||Kickoff tahunan', 'p' => 'The format is reusable year to year — only the content template data changes.||Formatnya bisa dipakai ulang tiap tahun — hanya data template konten yang berubah.'],
            ['h' => 'Regional roadshows||Roadshow regional', 'p' => 'A scaled-down stage kit runs the same show for 150-person regional sessions.||Kit panggung versi kecil menjalankan acara yang sama untuk sesi regional 150 orang.'],
            ['h' => 'Internal comms||Komunikasi internal', 'p' => 'Recap film and stage content feed the internal channel for the following quarter.||Film rekap dan konten panggung mengisi kanal internal selama kuartal berikutnya.'],
        ],
        'credits' => [
            ['role' => 'Event concept||Konsep acara', 'name' => 'Fugo Events'],
            ['role' => 'Stage & production||Panggung & produksi', 'name' => 'Fugo Events'],
            ['role' => 'Live content||Konten live', 'name' => 'Fugo Design'],
            ['role' => 'Documentation||Dokumentasi', 'name' => 'Fugo Production House'],
        ],
        'case_study' => null,
    ],

    [
        'slug' => 'suzuki-product-launch-coverage',
        'title' => 'Product Launch Coverage',
        'client' => 'Suzuki',
        'logo' => 'assets/img/clients/suzuki.webp',
        'category' => 'Production',
        'division' => 'Production House||Rumah Produksi',
        'year' => '2024',
        'scope' => 'Multi-cam — Live cut — Same-day edit||Multi-cam — Live cut — Edit hari yang sama',
        'bg' => '#141b2e',
        'accent' => '#4b5cff',
        'tags' => ['Multi-camera', 'Live', 'Same-day edit', 'Press kit'],
        'lede' => 'A launch covered live, cut on site, and published before the press left the building.||Peluncuran diliput langsung, diedit di lokasi, dan tayang sebelum pers meninggalkan gedung.',
        'about' => [
            'Launch coverage is usually delivered a week late, when the news cycle has already closed. The value is entirely in speed — a perfect film published on Friday is worth less than a good one published at 4pm.||Liputan peluncuran biasanya dikirim seminggu kemudian, saat siklus berita sudah tutup. Nilainya sepenuhnya ada pada kecepatan — film sempurna yang tayang Jumat kalah nilai dari film bagus yang tayang pukul empat sore.',
            'We ran a five-camera setup feeding an on-site edit bay, so the recap, the press cutdown and the social clips were finished within the event itself.||Kami menjalankan lima kamera yang memasok bay editing di lokasi, sehingga rekap, cutdown pers, dan klip sosial selesai di dalam acara itu sendiri.',
        ],
        'steps' => [
            ['h' => 'Five cameras, one timecode||Lima kamera, satu timecode', 'p' => 'Jam-synced sources meant the edit started assembling while the event was still running.||Sumber yang tersinkron jam membuat proses edit sudah menyusun saat acara masih berlangsung.'],
            ['h' => 'On-site edit bay||Bay editing di lokasi', 'p' => 'An editor worked from the venue on a pre-built timeline with graphics already in place.||Editor bekerja dari venue pada timeline yang sudah disiapkan lengkap dengan grafis.'],
            ['h' => 'Published the same day||Tayang di hari yang sama', 'p' => 'The recap, a press-ready cutdown and six vertical clips were delivered before the room emptied.||Rekap, cutdown siap pers, dan enam klip vertikal dikirim sebelum ruangan kosong.'],
        ],
        'stats' => [
            ['n' => '5', 'l' => 'Cameras on the floor||Kamera di lokasi'],
            ['n' => '6', 'l' => 'Vertical clips same day||Klip vertikal di hari sama'],
            ['n' => '4', 'suffix' => 'h', 'l' => 'Event end to publish||Acara usai ke tayang'],
            ['n' => '1', 'l' => 'On-site edit bay||Bay editing di lokasi'],
        ],
        'gallery' => [
            ['kind' => 'Film||Film', 'cap' => 'Same-day launch recap||Rekap peluncuran hari-H', 'video' => true],
            ['kind' => 'Still||Foto', 'cap' => 'Reveal moment||Momen reveal'],
            ['kind' => 'Process||Proses', 'cap' => 'Five-camera floor plan||Denah lima kamera'],
            ['kind' => 'Process||Proses', 'cap' => 'On-site edit bay||Bay editing di lokasi'],
            ['kind' => 'Still||Foto', 'cap' => 'Press wall and interviews||Press wall dan wawancara'],
            ['kind' => 'Cutdown||Cutdown', 'cap' => 'Vertical social clip set||Set klip sosial vertikal', 'video' => true],
        ],
        'docs' => [
            ['label' => 'Coverage plan & camera map||Rencana liputan & peta kamera', 'meta' => 'PDF'],
            ['label' => 'Same-day delivery schedule||Jadwal delivery hari-H', 'meta' => 'PDF'],
            ['label' => 'Press kit — stills & clips||Press kit — foto & klip', 'meta' => 'ZIP'],
            ['label' => 'Archive and footage index||Indeks arsip & footage', 'meta' => 'XLSX'],
        ],
        'usecases' => [
            ['h' => 'Press distribution||Distribusi pers', 'p' => 'Broadcast-ready cutdowns and stills were sent to media within the same news cycle.||Cutdown siap siar dan foto dikirim ke media dalam siklus berita yang sama.'],
            ['h' => 'Dealer network||Jaringan dealer', 'p' => 'Dealers received the recap and clips for local posting the same evening.||Dealer menerima rekap dan klip untuk unggahan lokal di malam yang sama.'],
            ['h' => 'Archive||Arsip', 'p' => 'Full multi-cam masters are indexed for later campaign re-use.||Master multi-cam lengkap diindeks untuk digunakan ulang di kampanye berikutnya.'],
        ],
        'credits' => [
            ['role' => 'Coverage direction||Pengarahan liputan', 'name' => 'Fugo Production House'],
            ['role' => 'Multi-camera crew||Kru multi-kamera', 'name' => 'Fugo Production House'],
            ['role' => 'On-site edit||Edit di lokasi', 'name' => 'Fugo Post'],
            ['role' => 'Client team||Tim klien', 'name' => 'Suzuki Marketing'],
        ],
        'case_study' => null,
    ],

    [
        'slug' => 'nutrigoat-brand-identity-refresh',
        'title' => 'Brand Identity Refresh',
        'client' => 'Nutrigoat',
        'logo' => null,
        'category' => 'Design',
        'division' => 'Design||Desain',
        'year' => '2025',
        'scope' => 'Identity — Packaging — Guidelines||Identitas — Kemasan — Panduan',
        'bg' => '#123a1e',
        'accent' => '#c8f24e',
        'tags' => ['Identity', 'Packaging', 'Guidelines', 'Retail'],
        'lede' => 'A shelf-first identity: designed to be read at two metres, in a fridge, next to eleven competitors.||Identitas yang mengutamakan rak: dirancang agar terbaca dari dua meter, di dalam kulkas, di antara sebelas kompetitor.',
        'about' => [
            'The old identity was designed for a logo presentation, not a shelf. At retail distance the name disappeared and the variant colours were indistinguishable under fridge lighting.||Identitas lama dirancang untuk presentasi logo, bukan untuk rak. Pada jarak ritel, namanya menghilang dan warna variannya tidak terbedakan di bawah lampu kulkas.',
            'We rebuilt the mark for small sizes first, then set a variant colour system tested under real fridge lighting before anything was printed.||Kami membangun ulang logo dari ukuran terkecil lebih dulu, lalu menyusun sistem warna varian yang diuji di bawah pencahayaan kulkas nyata sebelum dicetak.',
        ],
        'steps' => [
            ['h' => 'Designed the smallest size first||Merancang dari ukuran terkecil', 'p' => 'The mark was approved at 8 mm before it was ever shown large.||Logo disetujui pada ukuran 8 mm sebelum pernah ditampilkan besar.'],
            ['h' => 'Tested colour in a real fridge||Menguji warna di kulkas nyata', 'p' => 'Variant colours were chosen under retail lighting, not on a calibrated monitor.||Warna varian dipilih di bawah pencahayaan ritel, bukan di monitor terkalibrasi.'],
            ['h' => 'Wrote guidelines people use||Menulis panduan yang benar-benar dipakai', 'p' => 'Twenty pages of decisions, not eighty pages of description — with a one-page version for vendors.||Dua puluh halaman keputusan, bukan delapan puluh halaman deskripsi — dengan versi satu halaman untuk vendor.'],
        ],
        'stats' => [
            ['n' => '8', 'suffix' => 'mm', 'l' => 'Smallest approved mark||Ukuran logo terkecil disetujui'],
            ['n' => '6', 'l' => 'Product variants||Varian produk'],
            ['n' => '20', 'l' => 'Guideline pages||Halaman panduan'],
            ['n' => '2', 'suffix' => 'm', 'l' => 'Shelf legibility distance||Jarak keterbacaan rak'],
        ],
        'gallery' => [
            ['kind' => 'Identity||Identitas', 'cap' => 'Primary mark and lock-ups||Logo utama dan lock-up'],
            ['kind' => 'System||Sistem', 'cap' => 'Variant colour system||Sistem warna varian'],
            ['kind' => 'Packaging||Kemasan', 'cap' => 'Bottle and carton range||Rentang botol dan karton'],
            ['kind' => 'Retail||Ritel', 'cap' => 'Shelf test at two metres||Uji rak pada jarak dua meter'],
            ['kind' => 'Print||Cetak', 'cap' => 'Label print proofs||Proof cetak label'],
            ['kind' => 'Guide||Panduan', 'cap' => 'One-page vendor sheet||Satu halaman untuk vendor'],
        ],
        'docs' => [
            ['label' => 'Brand guideline||Panduan brand', 'meta' => 'PDF — 20 pages||PDF — 20 halaman'],
            ['label' => 'Logo pack||Paket logo', 'meta' => 'AI / SVG / PNG'],
            ['label' => 'Packaging dielines||Dieline kemasan', 'meta' => 'AI / PDF'],
            ['label' => 'Vendor one-pager||Satu halaman vendor', 'meta' => 'PDF'],
        ],
        'usecases' => [
            ['h' => 'Retail shelf||Rak ritel', 'p' => 'Variant colours stay distinct under fridge lighting at browsing distance.||Warna varian tetap berbeda di bawah lampu kulkas pada jarak melihat-lihat.'],
            ['h' => 'E-commerce||E-commerce', 'p' => 'The mark holds at marketplace thumbnail size without a separate digital logo.||Logo tetap terbaca pada ukuran thumbnail marketplace tanpa versi digital terpisah.'],
            ['h' => 'Vendor printing||Cetak vendor', 'p' => 'The one-page sheet keeps third-party printers on spec without a design review.||Satu halaman panduan menjaga percetakan pihak ketiga tetap sesuai spesifikasi tanpa review desain.'],
        ],
        'credits' => [
            ['role' => 'Identity design||Desain identitas', 'name' => 'Fugo Design'],
            ['role' => 'Packaging||Kemasan', 'name' => 'Fugo Design'],
            ['role' => 'Guidelines||Panduan', 'name' => 'Fugo Brand Ops'],
            ['role' => 'Client team||Tim klien', 'name' => 'Nutrigoat'],
        ],
        'case_study' => null,
    ],
];
